### ISSUE TITLE
All properties that are not defined in YAML should be removed in ndjson at the `filter` command

### ISSUE THREAD

**Issue by miya0001** [unvt/kata#10]
All properties other than `SOVEREIGNT` should be removed if a YAML like following is passed?

```
countries:
  source: ./ne_110m_admin_0_countries.shp.geojson
  minzoom: 0
  maxzoom: 5
  properties:
    name: properties.SOVEREIGNT
```
